spring.application.name=BlackFrame


#Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/BlackFrameDB
spring.datasource.username=root
spring.datasource.password=mysql123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Storage 
video.storage.location=C:/Uploads/videos/

#Upload Limits
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB